[package]
name = "liborca"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.14"

[lib]
name = "liborca"

[features]
default = ["participant_obstacles"]
# feature for using the participant obstacles
participant_obstacles = []
