name: Build Rust Agent

on: [push]

jobs:
  build_rust_agent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        working-directory: ./examples/scripts/rust-orca/
        with:
          command: build
          args: --release
