name: Evaluate

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Update packages
        run: sudo apt update
      - name: Build Application
        run: make terminal
